PROC CONTENTS DATA=MYDATA.IOWA_AVOCADO_PRICE; 
RUN;

/* Descriptive statistics of our dataset */
PROC MEANS DATA=MYDATA.IOWA_AVOCADO_PRICE MEAN MEDIAN STD MIN MAX;
RUN;

/* Missing values in our dataset */
PROC MEANS DATA=MYDATA.IOWA_AVOCADO_PRICE NMISS;
RUN;

/* Unique values for 2 columns */
PROC SQL;
SELECT COUNT(DISTINCT 'Type'n) AS 'Type'n,
       COUNT(DISTINCT 'region'n) AS 'Region'n
  FROM MYDATA.IOWA_AVOCADO_PRICE;
QUIT;

PROC FREQ DATA=MYDATA.IOWA_AVOCADO_PRICE;
	TABLES Type;
RUN;

PROC FREQ DATA=MYDATA.IOWA_AVOCADO_PRICE 
	ORDER=FREQ;
 	TABLES Type /
 	NOCOL NOROW NOPERCENT OUT=type_freg;
RUN;

PROC CORR DATA=MYDATA.IOWA_AVOCADO_PRICE PLOTS=SCATTER(NVAR=ALL);
   VAR AveragePrice TotalVolume LargeBags SmallBags XLargeBags TotalBags year;
RUN;

/* Checking Relationship between two variables by using scatter plot */
ODS GRAPHICS / RESET WIDTH=6.4IN HEIGHT=4.8IN IMAGEMAP;
PROC SGPLOT DATA=MYDATA.IOWA_AVOCADO_PRICE;
	SCATTER X='TotalVolume'n Y='LargeBags'n /;
	XAXIS GRID;
	YAXIS GRID;
RUN;
ODS GRAPHICS / RESET;

PROC SGPLOT DATA=MYDATA.IOWA_AVOCADO_PRICE;
	SCATTER X='TotalVolume'n Y='SmallBags'n /;
	XAXIS GRID;
	YAXIS GRID;
RUN;
ODS GRAPHICS / RESET;

PROC SGPLOT DATA=MYDATA.IOWA_AVOCADO_PRICE;
	SCATTER X='TotalVolume'n Y='TotalBags'n /;
	XAXIS GRID;
	YAXIS GRID;
RUN;
ODS GRAPHICS / RESET;

PROC UNIVARIATE DATA=MYDATA.IOWA_AVOCADO_PRICE;
	VAR AveragePrice;
	HISTOGRAM;
RUN;

/* Explore the target variable */
PROC UNIVARIATE DATA=TRAIN; VAR AveragePrice; HISTOGRAM ; RUN;


/* Eliminate outliers and create log transformed price variable */
DATA AveragePrice;
   SET TRAIN;
   WHERE 30 le AveragePrice le 750;
   Average_Price_Log = LOG(AveragePrice);
RUN;

PROC UNIVARIATE DATA=WORK.AveragePrice; 
   VAR AveragePrice; 
   HISTOGRAM; 
RUN;

PROC UNIVARIATE DATA=WORK.AveragePrice; VAR Average_Price_Log; HISTOGRAM; RUN;


PROC MEANS DATA=AveragePrice (KEEP = _NUMERIC_) N NMISS MIN MAX MEAN MEDIAN STD; RUN;

PROC BOXPLOT DATA=MYDATA.IOWA_AVOCADO_PRICE;
	PLOT AveragePrice*Type;
RUN;

PROC MEANS DATA=MYDATA.IOWA_AVOCADO_PRICE; 
	VAR AveragePrice;
RUN;

PROC MEANS DATA=MYDATA.IOWA_AVOCADO_PRICE N NMISS MIN MAX MEAN MEDIAN STDDEV;
	CLASS Type;
	VAR AveragePrice;
	OUTPUT OUT=list_stats;
RUN;

PROC SUMMARY DATA=MYDATA.IOWA_AVOCADO_PRICE;
	VAR AveragePrice;
	OUTPUT OUT=list_sum;

PROC SORT DATA=MYDATA.IOWA_AVOCADO_PRICE 
	OUT=list_sort;
	BY Type;
RUN;
 
PROC SUMMARY DATA=list_sort;
 	BY Type;
 	VAR AveragePrice;
 	OUTPUT OUT=list_sum SUM=;
RUN;

DATA WORK.TEST;
	SET MYDATA.IOWA_AVOCADO_PRICE;
	WHERE AveragePrice le 10000;
RUN;

DATA WORK.TEST;
	SET MYDATA.IOWA_AVOCADO_PRICE;
	IF AveragePrice le 10000;
RUN;

/* Split data into TRAIN and TEST datasets at an 70/30 split */
PROC SURVEYSELECT DATA=MYDATA.IOWA_AVOCADO_PRICE 
	SAMPRATE=0.30 SEED=42
	OUT=Full OUTALL METHOD=SRS;
RUN;

DATA TRAIN TEST;
	SET FULL;
	IF SELECTED=0 THEN OUTPUT TRAIN; ELSE OUTPUT TEST;
	DROP Selected;