LIBNAME MYDATA BASE "/home/u61270967/sasuser.v94";

FILENAME REFFILE '/home/u61270967/sasuser.v94/Iowa_Department_Avocado_Price.csv';

PROC IMPORT DATAFILE=REFFILE
 DBMS=CSV
 OUT= MYDATA.IOWA_AVOCADO_PRICE;
 GETNAMES=YES;
 
RUN;

PROC CONTENTS DATA=MYDATA.IOWA_AVOCADO_PRICE; RUN;

DATA WORK.TEST;
 SET MYDATA.IOWA_AVOCADO_PRICE;
RUN;

DATA TEST;
 SET MYDATA.IOWA_AVOCADO_PRICE;
RUN;
